language: ruby
rvm:
  - 2.5.3
script:
  - bundle exec jekyll build --future
  #- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer