language: ruby
cache:
  - bundler
  - directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
rvm:
- 2.5.4

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: _build/build.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

branches:
  only:
    - gh-pages
    - /.*/

# Add slack notifications
notifications:
  email: false